<?xml version="1.0"?>
<package format="2">
  <name>rox_bringup</name>
  <version>0.1.0</version>
  <description>ROS 1 bringup package for ROX robots</description>

  <maintainer email="ros@neobotix.de">Pradheep Padmanabhan</maintainer>
  <license>BSD</license>
  <url type="website">http://www.neobotix-robots.com</url>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>topic_tools</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>ros_gz
  </exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>sick_safetyscanners_base</exec_depend>
  <exec_depend>sick_safetyscanners2_interfaces</exec_depend>
  <exec_depend>sick_safetyscanners2</exec_depend>
  <exec_depend>phidgets_drivers</exec_depend>
  <exec_depend>neo_relayboard_v3</exec_depend>

</package>
