<?xml version="1.0"?>
<package format="2">
  <name>rox_rviz</name>
  <version>0.1.0</version>
  <description>ROS 1 - Visualization package for ROX robots</description>

  <maintainer email="ros@neobotix.de">Neobotix</maintainer>
  <license>BSD</license>
  <url type="website">http://www.neobotix-robots.com</url>
  <author email="padmanabhan@neobotix.de">Pradheep Padmanabhan</author>

  <buildtool_depend>catkin</buildtool_depend>

</package>