controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    linear_axis_controller:
      type: joint_trajectory_controller/JointTrajectoryController

linear_axis_controller:
  ros__parameters:
    joints:
      - linear_axis_slide_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      linear_axis_slide_joint: { trajectory: 0.2, goal: 0.1 }
